server:
  port: 8765
# config bus
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters: TokenRelay
      routes:
        id: lks-service
        uri: lb://lks-service
        predicates:
          Path: /lks
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://n1.stonsrl.com:8206/auth/realms/micro2-test-realm
        registration:
          micro2-cloud-gateway-client:
            client-id: micro2-cloud-gateway-client
            client-secret: d95988e0-567e-4c26-8c67-2188b63cfc33
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8765/login/oauth2/code/micro2-cloud-gateway-client
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# Define the Eureka server that handles service registration
#eureka:
  #client:
    #serviceUrl:
      #defaultZone: http://root:s3cr3t@localhost:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
  #instance:
    #instance-id: ${spring.application.name}-${random.uuid}
