server:
  port: 8761
spring:
  security:
    user:
      name: root
      password: s3cr3t
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://actuator:password@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://root:s3cr3t@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
